name = "cayesdesk-agent"
main = "cayesdesk-agent-worker.js"
compatibility_date = "2026-04-28"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true

[observability.traces]
enabled = true
head_sampling_rate = 1

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[kv_namespaces]]
binding = "eleven_labs_agent_tools"
id = "7561564432af4cd8a9006afb384d3f19"
