name = "cayesdesk-agent"
main = "cayesdesk-agent-worker.js"
compatibility_date = "2026-04-28"

[observability]
enabled = true

[observability.logs]
enabled = true
invocation_logs = true

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[kv_namespaces]]
binding = "eleven_labs_agent_tools"
id = "7561564432af4cd8a9006afb384d3f19"
