name = "cayesdesk-agent"
account_id = "61dd8de53dcc6ea9ba7fab9c9581564d"
pages_build_output_dir = "dist"
compatibility_date = "2026-04-28"

[[kv_namespaces]]
binding = "eleven_labs_agent_tools"
id = "7561564432af4cd8a9006afb384d3f19"
